### ISSUE TITLE
Full justification breaks when typing in empty chapters

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#343] opened 2016-09-29 07:10 UTC
The full justification setting in the visual editor creates a screwy layout when typing in a new chapter. I think the verse markers have some collection of styling that is not allowing line breaks, so the trailing edge of the paragraph cannot be split. This creates an issue on the second to last line of a paragraph where it stretches across the screen. Besides being ugly it's difficult to use because you are constantly typing on the last line but each word jumps to fill the previous line as you type.

![selection_250](https://cloud.githubusercontent.com/assets/173595/18944219/deb3730a-862c-11e6-8738-d623db4f85c6.png)

**Comment by teusbenschop** [comment] 2016-09-29 16:45
Here is some communications about it:

https://groups.google.com/forum/#!searchin/bibledit-general/justification%7Csort:relevance/bibledit-general/L0s_BDa3_qY/jqp5zLtSAQAJ

**Comment by alerque** [comment] 2016-09-29 17:48
The work around mentioned there shouldn't be necessary. Justified styling should work just fine to type in without jumping around. The issue here is the last splittable "word" in the paragraph is too long due to the verse references and other things with white-space handling set to nowrap. With that issue fixed the positioning wouldn't jump around very much (web browser's aren't smart enough to do really through break optimization.

**Comment by teusbenschop** [comment] 2016-09-29 17:56
If some CCS-ing around could change this behaviour, that would be great.

**Comment by teusbenschop** [comment] 2016-10-31 11:33
I am trying to reproduce this for making a fix, but fail to do so. What's the steps to take, starting from a clean Bibledit Cloud instance, to reproduce the symptoms?

**Comment by teusbenschop** [comment] 2016-12-13 10:14
This issue is less and less likely to come up in the future because the new default stylesheet that comes with the app has full justification off by default, anywhere. So a user who will encounter this will have specifically switched full justification on, and most users won't know how to do that.

Is it okay to close this issue?

**Closed as completed** 2016-12-13 11:02 UTC
